### ISSUE TITLE
Not working on 3.3.X

### ISSUE THREAD

**Issue by dldrk** [rundeck-plugins/rundeck-puppetenterprise-nodes-plugin#15]
Current version of this plugin is not able to work with Rundeck 3.3.X. Although it can work on 3.2.X.
As the errors seems related to log4j class, replacing the log4j2 for log4j.properties in rundeck-config and the file itself in /etc/rundeck, doesn't work also.

**Environment:**
3.3.7 RPM install
Postgres DB

**Snipped logs:**

com.dtolabs.rundeck.core.plugins.PluginException: Error loading class: com.rundeck.plugin.resources.puppetdb.ResourceModelFactory
	at com.dtolabs.rundeck.core.plugins.JarPluginProviderLoader.loadClass(JarPluginProviderLoader.java:440)

Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at com.rundeck.plugin.resources.puppetdb.ResourceModelFactory.<clinit>(ResourceModelFactory.java:62)
	at java.lang.Class.forName0(Native Method)Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.rundeck.plugin.resources.puppetdb.ResourceModelFactory
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
